[[DeviceList]]
  Name = "laptop"
  ProfileName = "laptop-profile"
  Description = "Example of Simple Device"
  Labels = [ "industrial" ]
  [DeviceList.Protocols]
  [DeviceList.Protocols.other]
    Address = "simple01"
    Port = "300"
  # [[DeviceList.AutoEvents]]
  #   Interval = "10s"
  #   OnChange = false
  #   SourceName = "Switch"
  # [[DeviceList.AutoEvents]]
  #   Interval = "30s"
  #   OnChange = false
  #   SourceName = "Image"
  [[DeviceList.AutoEvents]]
    Interval = "1s"
    OnChange = false
    SourceName = "temperature"
